apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-frontend-image:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: html-volume
              mountPath: /usr/share/nginx/html/env.js
              subPath: env.js
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "window._env_ = { REACT_APP_API_BASE_URL: '$(cat /config/REACT_APP_API_BASE_URL)' };" > /usr/share/nginx/html/env.js &&
              nginx -g 'daemon off;'
      volumes:
        - name: config-volume
          configMap:
            name: frontend-config
        - name: html-volume
          emptyDir: {}
